name: 'Test cl+ssl'

on:
  workflow_dispatch:
  push:
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-cl-plus-ssl:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: mkdir ${{ github.workspace }}/docker-home
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/docker-home/cl-plus-ssl
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}/docker-home/cl-plus-ssl
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Fetching OpenSSL (and LibreSSL) release binaries
        run: |
          cd ${{ github.workspace }}/docker-home/cl-plus-ssl/test/run-on-many-lisps-and-openssls/openssl-releases/
          ./bin-fetch.sh
      - run: |
          docker run -i --mount type=bind,source=${{ github.workspace }}/docker-home,target=/home/cl/ clfoundation/cl-devel:2022-02-09 unpack-default-home-dir
      - run: |
          docker run -i --mount type=bind,source=${{ github.workspace }}/docker-home,target=/home/cl/ clfoundation/cl-devel:2022-02-09 ls /home/cl/cl-plus-ssl/test/run-on-many-lisps-and-openssls/openssl-releases/
      - run: |
          docker run -e "LIB_LOAD_MODE=new" -e "OPENSSL=openssl-1.1.1f" -e "BITS=64" -i --mount type=bind,source=${{ github.workspace }}/docker-home,target=/home/cl/ clfoundation/cl-devel:2022-02-09 /home/cl/cl-plus-ssl/test/run-for-ci.sh
